### ISSUE TITLE
Where to include the GraphQL Playground endpoint?

### ISSUE THREAD

**Issue by itsandreramon** [maximivanov/azure-function-graphql-typescript-starter#1]
Hey, I am considering to use this starter in my next project. What would be the best way to include a second endpoint for the Playground to test my queries?

Thanks in advance!

**Comment by itsandreramon** [comment]
Just saw that its available as well under /graphql :D

**Comment by maximivanov** [comment]
Yep Playground is on by default in non-prod environments: https://www.apollographql.com/docs/apollo-server/testing/graphql-playground/

Good luck with your next project! Let me know if you find a way to improve the starter kit 😉
