### ISSUE TITLE
How would you implement security mechanisms?

### ISSUE THREAD

**Issue by itsandreramon** [maximivanov/azure-function-graphql-typescript-starter#2]
Hi, I used your starter and am very happy with it. However, I am currently figuring the best way to authenticate against it from my Android App. What would be the recommended way? Thanks!

**Comment by itsandreramon** [comment]
I am using Firebase Auth on Android btw

**Comment by maximivanov** [comment]
Hey @itsandreramon . Glad you find this starter kit useful!

If I get it right, your task boils down to verifying JWTs that you receive from authentication provider in headers. If that's the case you can do this in the context hook before resolvers are executed:

```js
context: async ({ context }): Promise<AppContext> => {
  const accessTokenPayload = await verifyAccessTokenFromHeaders(
    context.req.headers,
  )

  const currentUserUuid = accessTokenPayload?.uuid
  ...
```

You can stop here or (if both authenticated and non-authenticated visitors are expected) you can do that in resolvers on a case by case basis. 

You may also take a look at TypeGraphQL's Authorization feature: https://typegraphql.com/docs/authorization.html

**Comment by itsandreramon** [comment]
I would have done it this way. How would I block the request now? Do I access the header in the correct way?

```
context: async ({ context }): Promise<AppContext> => {
    const verified = await verifyAccessTokenFromHeaders(
      context.req.headers.authorization || '',
    )

    if (verified === true) {
          ??? what to do now?
    }

    return {
      conn,
      azureContext: context,
    }
...
}
```

**Comment by itsandreramon** [comment]
(sorry I am not a js developer normally)

**Comment by maximivanov** [comment]
Honestly I haven't touched Apollo GraphQL in a while so can't tell from memory on how to do this.

If you want to block all unauthenticated users, I'd try throwing an exception from the context hook (there was some exception class related to Authentication in Apollo). It may be all you need to do.

If you need to catch the error and modify is some way, try adding this on the same level as `context: ...`

```js
  formatError: (err) => {
    ...
  }
```

**Comment by itsandreramon** [comment]
Thank you! It works, I am throwing a Authentication Exception if verified is false. 👍🏻
